# Generated by Django 3.0.5 on 2020-05-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='end_date',
            field=models.DateField(default=None),
        ),
    ]
