# Generated by Django 3.0.6 on 2020-05-07 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0004_auto_20200507_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='end_date',
        ),
        migrations.AddField(
            model_name='streak',
            name='last_updated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
